apiVersion: v1
kind: Secret
metadata:
  name: {{.AddonName}}
  labels:
    app: {{.AppName}}
    apps: {{.AddonName}}
type: Opaque
data:
  mariadb-root-password: YXBwc1Jvb3RQd2Q=
  mariadb-password: YXBwc1B3ZA==
---
apiVersion: v1
kind: Service
metadata:
  name: {{.AddonName}}
  labels:
    app: {{.AppName}}
    apps: {{.AddonName}}
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    apps: {{.AddonName}}
  type: ClusterIP
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.AddonName}}-mariadb-pv-claim
  labels:
    app: {{.AppName}}
    apps: {{.AddonName}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "standard"
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{.AddonName}}
  labels:
    app: {{.AppName}}
    apps: {{.AddonName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: {{.AddonName}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps: {{.AddonName}}
    spec:
      containers:
      - name: {{.AddonName}}
        image: "mariadb:10.2"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.AddonName}}
              key: mariadb-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.AddonName}}
              key: mariadb-password
        - name: MYSQL_USER
          value: apps-user
        - name: MYSQL_DATABASE
          value: apps-db
        ports:
        - name: mariadb
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{.AddonName}}-mariadb-pv-claim

